version: '3.7'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql_host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: codo_codo
      MYSQL_DATABASE: pelicula_db
    ports:
      - 3306:3306

  web:
  # netlify
  # github_pages
    image: httpd:latest
    container_name: web
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  django:
    build: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
