version: '3.1'

services:

  db:
    container_name: mysql_server
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coderhouse
    ports:
      - 3306:3306
    # volumes:
      # - ./sql_database_answers:/sql_database_answers
  adminer:
    image: adminer
    container_name: mysql_client
    restart: always
    ports:
      - 8080:8080
    