version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coderhouse
    ports:
      - 3306:3306
    volumes:
      - ./sql_database_answers:/sql_database_answers
  adminer:
    image: adminer
    container_name: mysql-client
    restart: always
    ports:
      - 8080:8080
    